### PR TITLE
Move rust-analyzer

### PR DESCRIPTION
**Pull request by Hofer-Julian**
This hopefully prevents r-a metadata leaking into appdata

### CODE REVIEW

**Comment by Hofer-Julian** [comment]
@bilelmoussaoui @gasinvein

**Comment by gasinvein** [comment]
I think this won't be needed after flathub/flatpak-external-data-checker#102, instead, you'll need to set `"is-main-source": true` on one of the Rust packages (probably the x86_64 one).

**Comment by Hofer-Julian** [comment]
Okay, will wait till this is merged then

**Comment by gasinvein** [comment]
Merged.

**Pull request closed without merging**
