### PR TITLE
Add append-path in readme

### PR DESCRIPTION
**Pull request by SeaDve**

### CODE REVIEW

**Comment by Hofer-Julian** [comment]
Interesting, Fractal the app I tested this on has `append-path`  and `append-ld-library-path` already set so I didn't notice that it is required.
Thanks @SeaDve.

But don't you need `/usr/lib/sdk/llvm13/bin` in `append-path`?

**Comment by bilelmoussaoui** [comment]
I would mention llvm13's readme here, it has all the necessary details already

**Comment by SeaDve** [comment]
> But don't you need /usr/lib/sdk/llvm13/bin in append-path?

It seems to not work without it in append-path

**Comment by bilelmoussaoui** [comment]
Thanks!

**Pull request merged**
