### PR TITLE
Update to 1.54.0

### PR DESCRIPTION
**Pull request by A6GibKm**

### CODE REVIEW

**Comment by gasinvein** [comment]
Why is this opened against beta branch?

If you don't mind, I'll cherry-pick your fix 916b25a to #67.

**Comment by A6GibKm** [comment]
Because this is the branch I target when developing :). To be honest I don't know whats the justification of my last commit but it compiles at least.

**Comment by gasinvein** [comment]
I suppose the Rust installer doesn't install `rust-analyzer` binary anymore.

**Comment by bilelmoussaoui** [comment]
> I suppose the Rust installer doesn't install `rust-analyzer` binary anymore.

that's probably a copy/paste from rust-nightly. I don't think rust-stable installs/ever installed rust-analyzer before

**Comment by bilelmoussaoui** [comment]
bot, build

**Comment by gasinvein** [comment]
> > I suppose the Rust installer doesn't install `rust-analyzer` binary anymore.
> 
> that's probably a copy/paste from rust-nightly. I don't think rust-stable installs/ever installed rust-analyzer before

Well, `rm` without `-f` worked on the `rust-analyzer` file before. Doesn't it meant that the file existed?

**Pull request merged**
